"use client";
import{useState,useTransition}from"react";import{toast}from"sonner";import{Plus}from"lucide-react";import{Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle}from"@/components/ui/dialog";import{Button}from"@/components/ui/button";import{Input}from"@/components/ui/input";import{Label}from"@/components/ui/label";import{Textarea}from"@/components/ui/textarea";import{Select,SelectContent,SelectItem,SelectTrigger,SelectValue}from"@/components/ui/select";import{saveCltTaskAction}from"@/lib/supabase/clt-actions";import{addDaysToKey,WEEKDAY_ORDER,WEEKDAY_SHORT}from"@/lib/tasks";import type{CltCompany}from"@/types/database.types";
function Segmented<T extends string>({value,options,onChange,disabled}:{value:T;options:{value:T;label:string}[];onChange:(v:T)=>void;disabled?:boolean}){return <div className="grid gap-1.5" style={{gridTemplateColumns:`repeat(${options.length},minmax(0,1fr))`}}>{options.map(o=><Button key={o.value} type="button" size="sm" variant={value===o.value?"default":"outline"} onClick={()=>onChange(o.value)} disabled={disabled} className="h-9">{o.label}</Button>)}</div>}
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo"}).format(new Date())}
export function NewCltTaskButton({companies}:{companies:CltCompany[]}){const[o,setO]=useState(false);return <><Button onClick={()=>setO(true)}><Plus className="h-4 w-4"/>Nova tarefa</Button><Dialog open={o} onOpenChange={setO}>{o&&<Form companies={companies} close={()=>setO(false)}/>}</Dialog></>}
function Form({companies,close}:{companies:CltCompany[];close:()=>void}){const[p,start]=useTransition(),[company,setCompany]=useState("none"),[title,setTitle]=useState(""),[kind,setKind]=useState<"dia"|"prazo">("dia"),[rec,setRec]=useState<"none"|"weekly">("none"),[date,setDate]=useState(today()),[time,setTime]=useState(""),[priority,setPriority]=useState<"normal"|"importante">("normal"),[week,setWeek]=useState<number[]>([]),[until,setUntil]=useState(""),[notes,setNotes]=useState("");const recurring=kind==="dia"&&rec==="weekly";function toggle(d:number){setWeek(w=>w.includes(d)?w.filter(x=>x!==d):[...w,d])}function submit(e:React.FormEvent){e.preventDefault();if(!title.trim())return toast.error("Dê um título para a tarefa.");if(recurring&&!week.length)return toast.error("Escolha pelo menos um dia da semana.");start(async()=>{const r=await saveCltTaskAction({companyId:company==="none"?undefined:company,title,kind,dueDate:recurring?"":date,time,priority,notes,recurrence:recurring?"weekly":"none",weekdays:recurring?week:[],recurrenceUntil:recurring?until:""});if(r.error)toast.error(r.error);else{toast.success(r.success);close()}})}
return <DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Nova tarefa do CLT</DialogTitle></DialogHeader><form onSubmit={submit} className="flex max-h-[75vh] flex-col gap-4 overflow-y-auto pr-1">
<div className="flex flex-col gap-1.5"><Label>Empresa</Label><Select value={company} onValueChange={setCompany} disabled={p}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Geral do CLT</SelectItem>{companies.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></div>
<div className="flex flex-col gap-1.5"><Label>Título *</Label><Input value={title} onChange={e=>setTitle(e.target.value)} disabled={p} autoFocus placeholder="Ex: Conferir campanha da SGIV"/></div>
<div className="flex flex-col gap-1.5"><Label>Tipo</Label><Segmented value={kind} onChange={v=>{setKind(v);if(v==="prazo")setRec("none")}} disabled={p} options={[{value:"dia",label:"Tarefa do dia"},{value:"prazo",label:"Com prazo"}]}/><p className="text-[11px] text-muted-foreground">{kind==="dia"?"Algo para fazer em um dia específico.":"Algo que precisa estar pronto até uma data."}</p></div>
{kind==="dia"&&<div className="flex flex-col gap-1.5"><Label>Repetir</Label><Segmented value={rec} onChange={setRec} disabled={p} options={[{value:"none",label:"Não repetir"},{value:"weekly",label:"Dias da semana"}]}/>{recurring&&<div className="grid grid-cols-7 gap-1">{WEEKDAY_ORDER.map(d=><Button key={d} type="button" size="sm" variant={week.includes(d)?"default":"outline"} onClick={()=>toggle(d)} className="h-9 px-0 text-xs">{WEEKDAY_SHORT[d]}</Button>)}</div>}</div>}
{!recurring&&<div className="flex flex-col gap-1.5"><Label>{kind==="dia"?"Data *":"Prazo"}</Label><Input type="date" value={date} onChange={e=>setDate(e.target.value)} disabled={p}/><div className="flex gap-1.5"><Button type="button" variant="outline" size="sm" onClick={()=>setDate(today())}>Hoje</Button><Button type="button" variant="outline" size="sm" onClick={()=>setDate(addDaysToKey(today(),1))}>Amanhã</Button>{kind==="prazo"&&date&&<Button type="button" variant="ghost" size="sm" onClick={()=>setDate("")}>Sem prazo</Button>}</div></div>}
<div className="flex flex-col gap-1.5"><Label>Horário</Label><Input type="time" value={time} onChange={e=>setTime(e.target.value)} disabled={p}/></div>
{recurring&&<div className="flex flex-col gap-1.5"><Label>Repetir até</Label><Input type="date" value={until} onChange={e=>setUntil(e.target.value)} disabled={p}/><p className="text-[11px] text-muted-foreground">Opcional. Sem data, continua repetindo até você encerrar.</p></div>}
<div className="flex flex-col gap-1.5"><Label>Prioridade</Label><Segmented value={priority} onChange={setPriority} disabled={p} options={[{value:"normal",label:"Normal"},{value:"importante",label:"Importante"}]}/>{priority==="importante"&&<p className="text-[11px] text-muted-foreground">Fica em destaque na área do Trabalho / CLT.</p>}</div>
<div className="flex flex-col gap-1.5"><Label>Observações</Label><Textarea value={notes} onChange={e=>setNotes(e.target.value)} disabled={p} rows={2}/></div>
<DialogFooter><Button type="button" variant="outline" onClick={close} disabled={p}>Cancelar</Button><Button type="submit" disabled={p}>{p?"Salvando…":"Criar tarefa"}</Button></DialogFooter></form></DialogContent>}