"use client";
import{useState,useTransition}from"react";import{toast}from"sonner";import{Plus}from"lucide-react";import{Button}from"@/components/ui/button";import{Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle}from"@/components/ui/dialog";import{Input}from"@/components/ui/input";import{Label}from"@/components/ui/label";import{Textarea}from"@/components/ui/textarea";import{Select,SelectContent,SelectItem,SelectTrigger,SelectValue}from"@/components/ui/select";import{saveCltTaskAction}from"@/lib/supabase/clt-actions";import type{CltCompany}from"@/types/database.types";
const days=[["0","Dom"],["1","Seg"],["2","Ter"],["3","Qua"],["4","Qui"],["5","Sex"],["6","Sáb"]];
export function NewCltTaskButton({companies}:{companies:CltCompany[]}){const[o,setO]=useState(false),[p,start]=useTransition(),[kind,setKind]=useState<"prazo"|"dia">("prazo"),[rec,setRec]=useState<"none"|"weekly">("none"),[week,setWeek]=useState<number[]>([]);
function submit(fd:FormData){start(async()=>{const company=String(fd.get("company")||"");const r=await saveCltTaskAction({companyId:company==="none"?undefined:company,title:String(fd.get("title")),kind,dueDate:String(fd.get("date")||""),time:String(fd.get("time")||""),priority:String(fd.get("priority")) as "normal"|"importante",notes:String(fd.get("notes")||""),recurrence:rec,weekdays:week,recurrenceUntil:String(fd.get("until")||"")});if(r.error)toast.error(r.error);else{toast.success(r.success);setO(false)}})}
return <><Button onClick={()=>setO(true)}><Plus className="h-4 w-4"/>Nova tarefa</Button><Dialog open={o} onOpenChange={setO}><DialogContent><DialogHeader><DialogTitle>Nova tarefa do CLT</DialogTitle></DialogHeader><form action={submit} className="grid gap-3">
<div><Label>Empresa</Label><Select name="company" defaultValue="none"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Geral do CLT</SelectItem>{companies.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></div>
<div><Label>Tarefa *</Label><Input name="title" required/></div>
<div><Label>Tipo</Label><Select value={kind} onValueChange={v=>setKind(v as "prazo"|"dia")}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="prazo">Com prazo</SelectItem><SelectItem value="dia">Tarefa do dia</SelectItem></SelectContent></Select></div>
<div><Label>Repetição</Label><Select value={rec} onValueChange={v=>setRec(v as "none"|"weekly")}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Não repetir</SelectItem><SelectItem value="weekly">Recorrente durante a semana</SelectItem></SelectContent></Select></div>
{rec==="weekly"?<><div><Label>Dias da semana</Label><div className="mt-2 flex flex-wrap gap-2">{days.map(([v,l])=><Button key={v} type="button" size="sm" variant={week.includes(+v)?"default":"outline"} onClick={()=>setWeek(w=>w.includes(+v)?w.filter(x=>x!==+v):[...w,+v])}>{l}</Button>)}</div></div><div className="grid grid-cols-2 gap-3"><div><Label>Horário</Label><Input name="time" type="time"/></div><div><Label>Repetir até (opcional)</Label><Input name="until" type="date"/></div></div></>:<div className="grid grid-cols-2 gap-3"><div><Label>{kind==="prazo"?"Prazo até":"Dia da tarefa"}</Label><Input name="date" type="date" required/></div><div><Label>Horário</Label><Input name="time" type="time"/></div></div>}
<div><Label>Prioridade</Label><Select name="priority" defaultValue="normal"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="normal">Normal</SelectItem><SelectItem value="importante">Importante</SelectItem></SelectContent></Select></div>
<div><Label>Observações</Label><Textarea name="notes"/></div><DialogFooter><Button disabled={p}>{p?"Salvando...":"Salvar tarefa"}</Button></DialogFooter></form></DialogContent></Dialog></>}